name: Github-Ci/CD

on:
  [push] 
jobs:
  apiRobotTest:
    name: Robot - API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Instal requirements
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-requests
      - name: Start test
        run: |
          python -m robot -i api test/RobotFrameWork/tc.robot
  postmanTest:
    name: Postman Test
    runs-on: ubuntu-latest
    steps: 
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Run Newman
        uses: matt-ball/newman-action@v1.0.2
        with: 
          collection: ${{ github.workspace }}/test/Postman/TestApi.json
          reporters: cli
      
    
